language: ruby
sudo: required

services:
  - docker

before_install:
  - docker build -t quarkus7/which-tram .

script:
  - docker run quarkus7/which-tram python test.py

after_success:
  - bash docker_push
  - docker login --username=_ --password=$HEROKU_KEY registry.heroku.com
  - docker tag quarkus7/which-tram registry.heroku.com/$HEROKU_APP_NAME/web
  - docker push registry.heroku.com/$HEROKU_APP_NAME/web
  - heroku container:release web


#deploy:
#  provider: heroku
#  app: which-tram
#  api_key:
#    secure: "$HEROKU_KEY"
